### ISSUE TITLE
error: failed to run custom build command for windows_x86_64_msvc v0.52.4

### ISSUE THREAD

**Issue by Guohao8** [gevulotnetwork/gevulot#140]
error: failed to run custom build command for `windows_x86_64_msvc v0.52.4`                                                                                                    

Caused by:
  could not execute process `C:\Users\Dell\AppData\Local\Temp\cargo-installWfEz4T\release\build\windows_x86_64_msvc-ad1ea0008856dd84\build-script-build` (never executed)      

Caused by:
  拒绝访问。 (os error 5)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `gevulot-cli v0.1.0 (https://github.com/gevulotnetwork/gevulot.git#0119c70a)`, intermediate artifacts can be found at `C:\Users\Dell\AppData\Local\Temp\cargo-installWfEz4T`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
PS F:\gevulot>

**Comment by Guohao8** [comment]
I get an error when installing the Gevulot CLI.

**Comment by Guohao8** [comment]
![微信截图_20240314221459](https://github.com/gevulotnetwork/gevulot/assets/52415881/c5cceab4-968e-4ec2-9a11-c7fd58533616)

**Comment by Guohao8** [comment]
The BUG just now has been solved because of the anti-virus software.

**Comment by Guohao8** [comment]
Now there is a new BUG

![image](https://github.com/gevulotnetwork/gevulot/assets/52415881/b6dc4f6b-26fb-4950-84a3-82e6a3dbcd56)

**Comment by tuommaki** [comment]
Did you try to build only the `gevulot-cli` crate or the whole project?

Currently, the Gevulot node won't build on other operating systems than Linux, due to libraries and system interfaces it uses. There are also no plans to change this in the foreseeable future.

**Comment by Guohao8** [comment]
> Did you try to build only the `gevulot-cli` crate or the whole project?
> 
> Currently, the Gevulot node won't build on other operating systems than Linux, due to libraries and system interfaces it uses. There are also no plans to change this in the foreseeable future.

I've solved this problem.
It's because I'm using a windows system. I changed it to a linux system and it ran normally.

**Comment by Guohao8** [comment]
> Did you try to build only the `gevulot-cli` crate or the whole project?
> 
> Currently, the Gevulot node won't build on other operating systems than Linux, due to libraries and system interfaces it uses. There are also no plans to change this in the foreseeable future.

Thank you very much for your reply.
